/* Automatically generated by './build/entry.js' */
import Demo from '../packages/demo/index.js';
import './styles/element-theme.scss';

const components = [
  Demo
]

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  install,
  Demo
}